image: java:8-jdk

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

doc:
  stage: build
  script:
    - ./gradlew javadoc
  artifacts:
    paths:
      - build/docs/javadoc
  only:
    - master

test:
  stage: test
  script:
    - unzip ext2fs.zip
    - ./gradlew test
  artifacts:
    reports:
      junit:
        - build/test-results/test/TEST-*.xml

pages:
  stage: deploy
  script:
    - mv build/docs/javadoc public
  artifacts:
    paths:
      - public
  dependencies:
    - doc
