/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gitlab.incognitojam.ext2;

import java.io.IOException;

public class App {
    App() throws IOException {
        Volume volume = new Volume("ext2fs");
    }

    public static void main(String[] args) throws IOException {
        new App();
    }
}
