/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gitlab.incognitojam.ext2;

import java.io.IOException;

public class App {
    private App() {
        try (Volume volume = new Volume("ext2fs")) {
            volume.printDebugInfo();
        } catch (IOException exception) {
            exception.printStackTrace();
        }
    }

    public static void main(String[] args) {
        new App();
    }
}
